### ISSUE TITLE
No module named 'nselib'

### ISSUE THREAD

**Issue by sudipbapiray** [RuchiTanmay/nselib#14]
pip install nselib

still getting the error
![NSELIB2](https://github.com/RuchiTanmay/nselib/assets/157189016/d1bffb6d-3364-4d8d-aded-93dedf365c15)
![NSELIB](https://github.com/RuchiTanmay/nselib/assets/157189016/872172dd-7222-48ea-9adb-f15561f352b4)

**Comment by ankit100ni** [comment]
A few things you may check here:

Check Python Version: Ensure that you are using the correct Python version where 'nselib' is installed. Sometimes, if you have multiple Python installations, the module might be installed in a different version than the one you're using in your code.
If you are on Mac- prese cmd+Shift+P, Python: Select Interpreter, and change the interpreter. 

Virtual Environment: If you're working in a virtual environment, make sure that the 'nselib' module is installed within that environment. Activate the virtual environment and then run your code.

Module Path: Check if the 'nselib' module is installed in the correct directory that Python is looking in. You can print out the sys.path variable in your code to see the list of directories Python searches for modules.

**Comment by RuchiTanmay** [comment]
Hi, Please Try with new version nselib 1.0
pip install nselib --upgrade
