### ISSUE TITLE
Request For Adding New Features

### ISSUE THREAD

**Issue by arindamss007** [RuchiTanmay/nselib#15]
Hi, Tanmay! I'm Arindam Saha. I have been using this tool for quite a while. You made an awesome tool to get NSE data. I have a small request for add some new feature like:

(i) Extract Live Stock Data with Indicators values.
(ii) Get High Quality Historical Data With Indicator Values.
(iii) If possible please also add indicator values support in this functions which already exist -> price_volume_data(), and ->price_volume_and_deliverable_position_data().

Thank you for your exceptional work on nselib. Your contribution has made a meaningful difference in the lives of users like myself, and I look forward to witnessing its continued evolution.

**Comment by RuchiTanmay** [comment]
Hi Arindam, sure I can add live stock data.. but all brokers like zerodha, angel etc provide live data more efficiently.. not much lag

**Comment by arindamss007** [comment]
Lag should not affect that much, because I want this feature for Machine
Learning & Prediction Purposes. So if you add this feature it will be more
helpful. Thank You again for making this awesome tool.

**Comment by RuchiTanmay** [comment]
In that case it is bater you can use yfinance library

**Comment by 100xspace** [comment]
Hi ,
When I tried [Nifty Microcap 250](https://www.niftyindices.com/indices/equity/broad-based-indices/nifty-microcap-250),
No data came.

**Comment by 100xspace** [comment]
Is there a way to list down all the indices available

**Comment by RuchiTanmay** [comment]
Hi, Please Try with new version nselib 1.0
pip install nselib --upgrade

**Comment by splunk-user1** [comment]
Hi, I'm running nselib 1.5. 

Getting error `JSONDecodeError: Expecting value: line 1 column 1 (char 0)` while trying list ALL available indices using `capital_market.market_watch_all_indices()`  ... is it because the end point (https://www.nseindia.com/api/allIndices)  changed or unavaliable ? Thanks in advance!
