### ISSUE TITLE
Warning in dataframe concatenation

### ISSUE THREAD

**Issue by madhuingit** [RuchiTanmay/nselib#16]
I see the below warning, ignore if its already addressed

Python311\Lib\site-packages\nselib\capital_market\capital_market_data.py:226: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  nse_df = pd.concat([nse_df, data_df], ignore_index=True)

**Comment by RuchiTanmay** [comment]
Hi, Please Try with new version nselib 1.0
pip install nselib --upgrade
