### ISSUE TITLE
fno_equity_list function in capital_market_data.py not working

### ISSUE THREAD

**Issue by nipun-shrivastava** [RuchiTanmay/nselib#21]
try:
        ind_data_df = pd.read_csv("https://archives.nseindia.com/content/fo/fo_mktlots.csv")
        data_df = pd.read_csv("https://archives.nseindia.com/content/fo/fo_mktlots.csv", skiprows=5)
        
The csv's in try block are no longer present at archives.nseindia.com

**Comment by RuchiTanmay** [comment]
Hi, Please Try with new version nselib 1.0
pip install nselib --upgrade
