### ISSUE TITLE
 module 'nselib.capital_market' has no attribute 'fii_dii_trading_activity'

### ISSUE THREAD

**Issue by Vansh-j** [RuchiTanmay/nselib#22]
Hello!!
i was trying to retrive FIIs & DIIs data from the 'fii_dii_trading_activity' function
but got this error

AttributeError:  module 'nselib.capital_market' has no attribute 'fii_dii_trading_activity'

did i made some mistake??
thanks in advance!!

**Comment by RuchiTanmay** [comment]
Hi, Please Try with new version nselib 1.0
pip install nselib --upgrade
