### ISSUE TITLE
Wrong historical data

### ISSUE THREAD

**Issue by Shivamiiitd** [RuchiTanmay/nselib#23]
I was checking historical data for HDFC and ICICI Bank for years before 2019. I am getting wrong stock and derivatives data and it is not matching with data available on nse. Also I don't know about other stocks/indexes as I have not checked their data yet.

**Comment by RuchiTanmay** [comment]
Hi, Please share the code you use to get historical data..

**Comment by RuchiTanmay** [comment]
Hi, Please Try with new version nselib 1.0
pip install nselib --upgrade

**Comment by Shivamiiitd** [comment]
Hi, I try upgrading the version, but still the data is incorrect. You can look at my code at the below link. Thanks.
https://colab.research.google.com/drive/10JvR32mzOjb6vV_pgCPBvf8Ejl9NLrjk?usp=sharing
