### ISSUE TITLE
Running parallel download for multiple stock data resulting in error 

### ISSUE THREAD

**Issue by MSB-MRI** [RuchiTanmay/nselib#26]
Hi, I recently found out this very useful library for NSE data download. I'm trying to download multiple stock historical data using joblib but encountering errors. Does these functions only allow single query at a time from server??

**Comment by RuchiTanmay** [comment]
Hi, yes it is for single stock,  you can use loop to extract date.
thank you..

**Comment by RuchiTanmay** [comment]
thank you for your comment..
