### ISSUE TITLE
Can't call the package "nselib"

### ISSUE THREAD

**Issue by apoorav-singh** [RuchiTanmay/nselib#27]
I am currently running on Python version 3.12.4 (Anaconda)
Running the commands locally.
I am attaching the packages currently installed in the environment
[package list.txt](https://github.com/user-attachments/files/16321286/package.list.txt)

Error Message: C:/Users/asdeo/anaconda3/envs/trade/Lib/site-packages/requests/__init__.py:86): RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(

![image](https://github.com/user-attachments/assets/395f9a75-d80f-4a65-94a7-d72c7e316758)

Let me know if you need more information.

**Comment by RuchiTanmay** [comment]
Hi Apoorva, Can you please try it with python 3.9 .. 
3.9 is more stable version.
