### ISSUE TITLE
not able to pull data from NSE

### ISSUE THREAD

**Issue by SMVSKN** [RuchiTanmay/nselib#34]
Getting data from NSE does not work.... Example:
 
x = derivatives.participant_wise_open_interest('16-09-2024')

gives error. Noticed some path changes on NSE website.

Current url:     url = f"https://archives.nseindia.com/content/nsccl/fao_participant_oi_{str(trade_date.strftime('%d%m%Y'))}.csv"
New url:          url = f"https://**nsearchives**.nseindia.com/content/nsccl/fao_participant_oi_{str(trade_date.strftime('%d%m%Y'))}.csv"

But after making this change, though the error goes away, it hangs for a long time and finally does not fetch anything.

**Comment by RuchiTanmay** [comment]
Hi, Thanks for your concern raised.. I will fix it soon

**Comment by RuchiTanmay** [comment]
The paths are updated, please try nselib v-1.2, upgrade your version.

**Comment by SMVSKN** [comment]
> Hi, any other function has this issue?

I think all functions would be affected. You need to search for the string and make changes everywhere. I still see some functions referring to older paths.
