### ISSUE TITLE
Function hangs....

### ISSUE THREAD

**Issue by SMVSKN** [RuchiTanmay/nselib#36]
Continuation of issue #34.

Thanks for the quick response.

I upgraded, but now it is hanging for a long time and not returning any result. Not sure about other functions.

I am using the following function:

x = derivatives.participant_wise_open_interest('16-09-2024')

Could you try at your end and make sure it works.

Also, the path changes dont seem to be done in all the functions. You may want to search for "archives" keyword all over the package and update everywhere.

Regards,
Srinivas

**Comment by SMVSKN** [comment]
Please ignore my previous post. I dont see the hang issue now in my local. But on AWS it is hanging. I will figure it out.

However, Kindly check if the following line also needs  to be updated:

This is in funtion fno_bhav_copy:
        url2 = "https://www.nseindia.com/api/reports?archives=" \
             "%5B%7B%22name%22%3A%22F%26O%20-%20Bhavcopy(csv)%22%2C%22type%22%3A%**22archives**%22%2C%22category%22" \
             f"%3A%22derivatives%22%2C%22section%22%3A%22equity%22%7D%5D&date={str(trade_date.strftime('%d-%b-%Y'))}" \
             f"&type=equity&mode=single"

**Comment by RuchiTanmay** [comment]
HI,
To understand your issue.. Cay we connect some time ..
my wp no: 9337477060

**Comment by RuchiTanmay** [comment]
this is working fine..
![Screenshot 2024-09-24 131251](https://github.com/user-attachments/assets/e4c85aad-6ec5-40d2-9298-4f2f4ed05e4d)

**Comment by SMVSKN** [comment]
Hi Thanks for your quick response. Is it the bhav copy function for which
you shared the image? If yes, it should be OK. I dont use that function, it
was just from code review I was guessing it may need a change. However, I
still have problems with AWS. I checked everything I could, but found no
issues. The python code is also same when I run locally from my machine and
when I run from aws. On the AWS, it does not get any data back even after
multiple seconds of waiting. I was searching on the web and found that
previously cloud accesses to NSE have had problems. For eg, for
nsepython library, the creators released the nsepythonserver version to
address the issue. Not sure if similar issue is there now for this library.

See attached screenshot where the code is trying to get fno participant OI
data... It hangs on the function call
derivatives.participant_wise_open_interest(dat_str).
Here, dat_str = '20-Sep-2024'

We can discuss this on whatsapp call tomorrow. Let me know what time would
be convenient for you

Regards

**Comment by SMVSKN** [comment]
Hi,
Now I tried from local machine. That is hanging too.... See snapshot below.
This was working earlier in the afternoon
