### ISSUE TITLE
ParserError since today morning

### ISSUE THREAD

**Issue by emailanalysts** [RuchiTanmay/nselib#37]
![nselib](https://github.com/user-attachments/assets/b979ce66-49cf-495a-90b6-20a237df6cc7)
 I am getting ParserError since today morning. Pls help in resolving this

**Comment by RuchiTanmay** [comment]
Some new updates are in nseindia site, we are resolving it soon.

**Comment by RuchiTanmay** [comment]
please upgrade nselib 1.3.. and try

**Comment by RuchiTanmay** [comment]
https://www.youtube.com/watch?v=T-ZcOg9PNcA
