### ISSUE TITLE
Nselib is not fetching data for anything

### ISSUE THREAD

**Issue by gettingalpha** [RuchiTanmay/nselib#39]
The issue started today at around 12:25

**Comment by gettingalpha** [comment]
yfinance was also facing this problem on 18th October, for Nse stock data, but they fixed it by evening

**Comment by RuchiTanmay** [comment]
Looks like the NSE website is going through some maintenance activity.. we will wait till Monday.. if it is not fixed .. then we will fix it . 
Thanks for informing us.

**Comment by RuchiTanmay** [comment]
Please upgrade to nselib 1.4,  all issue resolved
