### ISSUE TITLE
Unable to fetch NIFTY 50 index data

### ISSUE THREAD

**Issue by DarakDir** [RuchiTanmay/nselib#42]
The below call is not working. Could you please check and help out ? Thanks

capital_market.index_data(index='NIFTY 50',from_date='19-10-2024', to_date='30-10-2024')

I'm using below
nselib 1.4
Python 3.12.4
urllib3 2.2.2

**Comment by RuchiTanmay** [comment]
Hi, 
19-10-2024 is saturday, no data available ..
plese try with below.
index_data(index='NIFTY 50', from_date='21-10-2024', to_date='30-10-2024')

**Comment by DarakDir** [comment]
Thanks @RuchiTanmay for helping out. But, I'm sorry to inform you that the below didn't work. Kindly help me out. Thanks !!

data = capital_market.index_data(index='NIFTY 50',from_date='22-10-2024', to_date='30-10-2024')

**Comment by RuchiTanmay** [comment]
issue fixed... Please upgrade to nselib 1.5

**Comment by DarakDir** [comment]
Thanks @RuchiTanmay :) It works now.
