### ISSUE TITLE
Unable to fetch options data on '1D' basis

### ISSUE THREAD

**Issue by Aravindh1895** [RuchiTanmay/nselib#43]
df1 = derivatives.option_price_volume_data('NIFTY', 'OPTIDX', option_type=option_type, period='1D')
i use this code to fetch previous day data daily but few times i've encountered errror stating : Timestamp not in the axis, i'm facing this issue sometimes not on regular basis, I don't know it's because of inconsistency of NSE portal or something else.
![Screenshot 2024-11-04 141517](https://github.com/user-attachments/assets/b6c8ddcf-ea2e-44a3-9198-1fbb931b784c)

**Comment by RuchiTanmay** [comment]
please check with below code.. remove option_type=option_type,
df1 = derivatives.option_price_volume_data('NIFTY', 'OPTIDX',  period='1D')

**Comment by Aravindh1895** [comment]
Yeah it's working now.....Thanks
